services:
  mizuno:
    container_name: mizuno
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./assets:/assets
    ports:
      - 4000:4000
      - 9230:9230
    restart: always
    depends_on:
      - postgres
    command: yarn start:dev
  postgres:
    container_name: mizuno-db
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env     
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
volumes:
  postgres: