version: "3.8"
services:
  bot:
    container_name: bot
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      # - ./node_modules:/app/node_modules
    ports:
      - 4000:4000
      - 9230:9230
    restart: always
    command: yarn start:dev
