services:
  mizuno:
    container_name: mizuno
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 4000:4000
      - 9230:9230
    restart: always
    command: yarn start:dev